///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_sensordatas.h
/// IMPLEMENTATION DATA TYPE NAME     : SensorDatas
/// GENERATED DATE                    : 2024-11-12 15:53:00
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_CPP_IMPL_TYPE_SENSORDATAS_H
#define PARA_ARA_COM_GEN_CPP_IMPL_TYPE_SENSORDATAS_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "deepracer/type/impl_type_left_camera.h"
#include "deepracer/type/impl_type_lidars.h"
#include "deepracer/type/impl_type_right_camera.h"
/// @uptrace{SWS_CM_10375}
namespace deepracer
{
namespace type
{
struct SensorDatas
{
    deepracer::type::lidars lidars;
    deepracer::type::left_camera left_camera;
    deepracer::type::right_camera right_camera;
    PARA_STRUCTURE(SensorDatas, lidars, left_camera, right_camera);
};
} /// namespace type
} /// namespace deepracer
#endif /// PARA_ARA_COM_GEN_CPP_IMPL_TYPE_SENSORDATAS_H