///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : calc.cpp
/// SOFTWARE COMPONENT NAME           : Calc
/// GENERATED DATE                    : 2024-11-12 15:53:00
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "calc/aa/calc.h"
#include <vector>
#include <utility> // std::pair 사용을 위해 추가
#include <random> // random test


std::pair<float, float> runModel(const std::vector<float>& lidar_data, const std::vector<float>& camera_data);
void initializeModelOnce();
 
#define DEBUG_SH 0
namespace calc
{
namespace aa
{
 
Calc::Calc()
    : m_running(false), m_event_flag(false)
    , m_logger(ara::log::CreateLogger("CALC", "SWC", ara::log::LogLevel::kVerbose))
    , m_workers(2)
{
}
 
Calc::~Calc()
{
}
 
bool Calc::Initialize()
{
    m_logger.LogVerbose() << "Calc::Initialize";
    
    bool init{true};

    m_ControlData = std::make_shared<calc::aa::port::ControlData>();
    m_RawData = std::make_shared<calc::aa::port::RawData>();
    
    return init;
}
 
void Calc::Start()
{
    m_logger.LogVerbose() << "Calc::Start";
    
    m_ControlData->Start();
    m_RawData->Start();
    m_running = true;
    // run software component
    //m_logger.LogInfo() << "----------------Calc Start----------------";
    Run();
}
 
void Calc::Terminate()
{
    m_logger.LogVerbose() << "Calc::Terminate";
    m_running = false;
    m_ControlData->Terminate();
    m_RawData->Terminate();
    m_event_flag = false;
}
 
void Calc::Run()
{
    m_running = true;
    m_logger.LogVerbose() << "Calc::Run";
    
    m_workers.Async([this] { ThrowEventCyclic(); });
    m_workers.Async([this] { TaskReceiveREventCyclic(); });
      
    m_workers.Wait();
}
 
void Calc::TaskReceiveREventCyclic()
{
    // init model;
    initializeModelOnce();
    m_RawData->SetReceiveEventREventHandler([this](const auto& sample)
    {
        OnReceiveREvent(sample);
    });
    m_RawData->ReceiveEventREventCyclic();
}

void Calc::OnReceiveREvent(const deepracer::service::rawdata::proxy::events::REvent::SampleType& sample)
{
    #if DEBUG_SH
    printf("ksh_@@@ [Calc] OnReceiveEvent [%lf]\n", sample.lidars.front().theta);
    #endif

    deepracer::type::lidars processed_lidars; // 0~ 360 8000개? 
    
    bool result = true;
    float start_degree = 150.0;
    float end_degree = 210.0;
    result = GetFrontLidarData(start_degree, end_degree, sample.lidars, &processed_lidars); // 150 ~ 210
    if (!result) {
        printf("ksh_@@@ SelecLidarRange Fail\n");
    }

    result = InterpolateLidarData(&processed_lidars); // 0인애들 보정해주고
    if (!result) {
        printf("ksh_@@@ InterpolateLidarData Fail\n");
    }
    
    std::vector<float> result_lidar;
    result_lidar = Extract8PointsForAI(start_degree, end_degree, &processed_lidars);

    std::vector<float> result_camera(120 * 160 * 2);

    std::random_device rd;
    std::mt19937 gen(rd()); // Standard mersenne_twister_engine
    std::uniform_real_distribution<> dis(0.0, 1.0); // Range between 0.0 and 1.0
    
    // Fill camera_data with random values
    for (auto& val : result_camera) {
        val = dis(gen);
    }


    std::pair<float, float> prediction = runModel(result_lidar, result_camera);

    printf("fuck Prediction Result: %f, %f\n", prediction.first, prediction.second);

    UpdateSteeringData(prediction);
}

bool Calc::GetFrontLidarData(float start_degree, float end_degree, const deepracer::type::lidars before_lidar, deepracer::type::lidars* after_lidar) {
    // printf ("ksh_@@@@@@ before select\n");
    // printf ("ksh_@@@@@@ ------------------\n");
    // for (int pos = 0; pos < before_lidar.size() ; ++pos) {
    //  printf("%s theta: %03.2f Dist: %08.2f Q: %d \n", 
    //             (before_lidar[pos].sync) ?"S ":"  ", 
    //             before_lidar[pos].theta,
    //             before_lidar[pos].dist,
    //             before_lidar[pos].quality);
    // }
    // printf ("ksh_@@@@@@ ------------------\n");
    
    for (auto& itr : before_lidar) {
        if ( (itr.theta >= start_degree) && (itr.theta <= end_degree) ) {
            after_lidar->push_back(itr);
        }
    }

    // printf ("ksh_@@@@@@ after select\n");
    // printf ("ksh_@@@@@@ ------------------\n");
    // for (int pos = 0; pos < after_lidar->size() ; ++pos) {
    //  printf("%s theta: %03.2f Dist: %08.2f Q: %d \n", 
    //             (after_lidar->at(pos).sync) ?"S ":"  ", 
    //             after_lidar->at(pos).theta,
    //             after_lidar->at(pos).dist,
    //             after_lidar->at(pos).quality);
    // }
    // printf ("ksh_@@@@@@ ------------------\n");

    return true;
}

bool Calc::InterpolateLidarData(deepracer::type::lidars* lidar_datas) {
    for (size_t i = 1; i < lidar_datas->size() - 1; ++i) {
        if (lidar_datas->at(i).dist == 0) {
            size_t prev = i - 1;
            size_t next = i + 1;
            while (next < lidar_datas->size() && (lidar_datas->at(next).dist == 0 )) {
                ++next;
            }
            if (next < lidar_datas->size()) {
                lidar_datas->at(i).dist = (lidar_datas->at(prev).dist + lidar_datas->at(next).dist) / 2;
            } else {
                lidar_datas->at(i).dist = lidar_datas->at(prev).dist; // Handle edge case if no valid next value
            }
        }
    }


    // printf ("ksh_@@@@@@ after Interpolat\n");
    // printf ("ksh_@@@@@@ ------------------\n");
    // for (int pos = 0; pos < lidar_datas->size() ; ++pos) {
    //  printf("%s theta: %03.2f Dist: %08.2f Q: %d \n", 
    //             (lidar_datas->at(pos).sync) ?"S ":"  ", 
    //             lidar_datas->at(pos).theta,
    //             lidar_datas->at(pos).dist,
    //             lidar_datas->at(pos).quality);
    // }
    // printf ("ksh_@@@@@@ ------------------\n");
    return true;
}

std::vector<float> Calc::Extract8PointsForAI(float start_degree, float end_degree, deepracer::type::lidars* lidar_datas) {
    std::vector<float> result;

    // 중간 지점과 각도를 계산
    float mid_degree = (start_degree + end_degree) / 2.0f;
    float interval = (end_degree - start_degree) / 8.0f;

    // 각 구간의 평균 거리값을 계산
    for (int i = 0; i < 8; ++i) {
        float lower_bound = start_degree + i * interval;
        float upper_bound = start_degree + (i + 1) * interval;

        std::vector<float> distances;
        
        for (auto& itr : *lidar_datas) {
            if ( (itr.theta >= lower_bound) && (itr.theta < upper_bound) ) {
                distances.push_back(itr.dist);
            }
        }

        if (!distances.empty()) {
            float sum = std::accumulate(distances.begin(), distances.end(), 0.0f);
            float avg = sum / distances.size();
            result.push_back(avg);
        } else {
            result.push_back(0.0f); // 해당 구간에 데이터가 없을 경우 기본값 0.0을 사용
        }
    }


    // printf("ksh_@@@ result lidar ");
    // for (auto itr : result) {
    //     printf(",[%.2f]", itr);
    // }
    // printf("    END\n");

    return result;
}

void Calc::UpdateSteeringData(std::pair<float, float> steerDatas)
{
    deepracer::service::controldata::skeleton::events::CEvent::SampleType controlData;
    controlData.cur_angle = steerDatas.first;
    controlData.cur_speed = steerDatas.second;

    m_ControlData->WriteDataCEvent(controlData);
    
    // Update RField
    std::lock_guard<std::mutex> lock(m_mutex); // m_event_flag 때문
    m_event_flag = true;
}



void Calc::ThrowEventCyclic() {
    while (m_running) {
	    // printf("ksh_@@@ [Calc] Start ThrowEventCyclic\n");
        //std::lock_guard<std::mutex> lock(m_mutex);
        if (m_event_flag == true) {
            std::lock_guard<std::mutex> lock(m_mutex);;
            printf("ksh_@@@ [Calc]ThrowEvent !!!\n");
            m_ControlData->SendEventCEventTriggered();
            m_event_flag = false;
        }

        std::this_thread::sleep_for(std::chrono::seconds(1)); // 1초보다 짧으면 좋을듯
	    // printf("ksh_@@@ [Calc] End ThrowEventCyclic Loop\n");
    }
}

} /// namespace aa
} /// namespace calc


