///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : sensor.h
/// SOFTWARE COMPONENT NAME           : Sensor
/// GENERATED DATE                    : 2024-11-12 15:53:00
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensor/aa/port/rawdata.h"
 
#include "para/swc/port_pool.h"

#include "lidar_driver.h"
#include "camera_driver.h"
namespace sensor
{
namespace aa
{
 
class Sensor
{
public:
    /// @brief Constructor
    Sensor();
    
    /// @brief Destructor
    ~Sensor();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();

    void UpdateDatas();
    bool UpdateLidarData();
    bool UpdateCameraData();

    void ThrowEventCyclic();
 
private:
    /// @brief Run software component
    void Run();
 
private:
    bool m_running;
    bool m_event_flag;
    std::mutex m_mutex;
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Sensor.RawData}
    std::shared_ptr<sensor::aa::port::RawData> m_RawData;

    /// @brief Instance of Port {Sensor.RawData}
    std::shared_ptr<LidarDriver> m_lidar_driver;
    std::shared_ptr<CameraDriver> m_camera_driver;
};
 
} /// namespace aa
} /// namespace sensor
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_SENSOR_AA_H