///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rawdata.cpp
/// SOFTWARE COMPONENT NAME           : RawData
/// GENERATED DATE                    : 2024-11-12 15:10:44
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "calc/aa/port/rawdata.h"
 
namespace calc
{
namespace aa
{
namespace port
{
 
RawData::RawData()
    : m_logger(ara::log::CreateLogger("CALC", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_found{false}
{
}
 
RawData::~RawData()
{
}
 
void RawData::Start()
{
    m_logger.LogVerbose() << "RawData::Start";
    
    // regist callback
    ara::core::InstanceSpecifier specifier{"Calc/AA/RawData"};
    auto handler = [this](ara::com::ServiceHandleContainer<deepracer::service::rawdata::proxy::SvRawDataProxy::HandleType> handles,
                          ara::com::FindServiceHandle findHandle) {
        this->Find(handles, findHandle);
    };
    
    // find service
    auto find = deepracer::service::rawdata::proxy::SvRawDataProxy::StartFindService(handler, specifier);
    if (find.HasValue())
    {
        m_logger.LogVerbose() << "RawData::Start::StartFindService";
    }
    else
    {
        m_logger.LogError() << "RawData::Start::StartFindService::" << find.Error().Message();
    }
    
    // run port
    m_running = true;
}
 
void RawData::Terminate()
{
    m_logger.LogVerbose() << "RawData::Terminate";
    
    // stop port
    m_running = false;
    
    // clear service proxy
    if (m_interface)
    {
        // stop subscribe
        StopSubscribeRLidarEvent();
        StopSubscribeRCameraEvent();
        StopSubscribeRField();
        
        // stop find service
        m_interface->StopFindService(*m_findHandle);
        m_found = false;
        
        m_logger.LogVerbose() << "RawData::Terminate::StopFindService";
    }
}
 
void RawData::Find(ara::com::ServiceHandleContainer<deepracer::service::rawdata::proxy::SvRawDataProxy::HandleType> handles, ara::com::FindServiceHandle findHandle)
{
    // check finding handles
    if (handles.empty())
    {
        m_logger.LogVerbose() << "RawData::Find::Service Instances not found";
        return;
    }
    else
    {
        for (auto& handle : handles)
        {
            m_logger.LogVerbose() << "RawData::Find::Searched Instance::ServiceId =" << 
                                     handle.GetServiceHandle().serviceId << 
                                     ", InstanceId =" << 
                                     handle.GetServiceHandle().instanceId;
        }
    }
    
    // create proxy
    if (m_interface)
    {
        m_logger.LogVerbose() << "RawData::Find::Proxy is already running";
    }
    else
    {
        m_logger.LogVerbose() << "RawData::Find::Using Instance::ServiceId =" << 
                                 handles[0].GetServiceHandle().serviceId << 
                                 ", InstanceId =" << 
                                 handles[0].GetServiceHandle().instanceId;
        m_interface = std::make_shared<deepracer::service::rawdata::proxy::SvRawDataProxy>(handles[0]);
        m_findHandle = std::make_shared<ara::com::FindServiceHandle>(findHandle);
        m_found = true;
        
        // subscribe events
        SubscribeRLidarEvent();
        SubscribeRCameraEvent();
        // subscribe field notifications
        SubscribeRField();
    }
}
 
void RawData::SubscribeRLidarEvent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // 
        // RegistReceiverRLidarEvent();
        
        // request subscribe
        auto subscribe = m_interface->RLidarEvent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "RawData::SubscribeRLidarEvent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RawData::SubscribeRLidarEvent::" << subscribe.Error().Message();
        }
    }
}
 
void RawData::StopSubscribeRLidarEvent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->RLidarEvent.Unsubscribe();
        m_logger.LogVerbose() << "RawData::StopSubscribeRLidarEvent::Unsubscribed";
    }
}
 
void RawData::RegistReceiverRLidarEvent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventRLidarEventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->RLidarEvent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "RawData::RegistReceiverRLidarEvent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RawData::RegistReceiverRLidarEvent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RawData::ReceiveEventRLidarEventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_interface->RLidarEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->RLidarEvent.GetNewSamples([&](auto samplePtr) {
                RawData::ReadDataRLidarEvent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "RawData::ReceiveEventRLidarEvent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RawData::ReceiveEventRLidarEvent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RawData::ReceiveEventRLidarEventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_found)
        {
            if (m_interface->RLidarEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->RLidarEvent.GetNewSamples([&](auto samplePtr) {
                    RawData::ReadDataRLidarEvent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "RawData::ReceiveEventRLidarEvent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RawData::ReceiveEventRLidarEvent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RawData::ReadDataRLidarEvent(ara::com::SamplePtr<deepracer::service::rawdata::proxy::events::RLidarEvent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    // put your logic
}
 
void RawData::SubscribeRCameraEvent()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // 
        // RegistReceiverRCameraEvent();
        
        // request subscribe
        auto subscribe = m_interface->RCameraEvent.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "RawData::SubscribeRCameraEvent::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RawData::SubscribeRCameraEvent::" << subscribe.Error().Message();
        }
    }
}
 
void RawData::StopSubscribeRCameraEvent()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->RCameraEvent.Unsubscribe();
        m_logger.LogVerbose() << "RawData::StopSubscribeRCameraEvent::Unsubscribed";
    }
}
 
void RawData::RegistReceiverRCameraEvent()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveEventRCameraEventTriggered();
        };
        
        // regist callback
        auto callback = m_interface->RCameraEvent.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "RawData::RegistReceiverRCameraEvent::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RawData::RegistReceiverRCameraEvent::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RawData::ReceiveEventRCameraEventTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_interface->RCameraEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->RCameraEvent.GetNewSamples([&](auto samplePtr) {
                RawData::ReadDataRCameraEvent(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "RawData::ReceiveEventRCameraEvent::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RawData::ReceiveEventRCameraEvent::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RawData::ReceiveEventRCameraEventCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_found)
        {
            if (m_interface->RCameraEvent.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->RCameraEvent.GetNewSamples([&](auto samplePtr) {
                    RawData::ReadDataRCameraEvent(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "RawData::ReceiveEventRCameraEvent::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RawData::ReceiveEventRCameraEvent::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RawData::ReadDataRCameraEvent(ara::com::SamplePtr<deepracer::service::rawdata::proxy::events::RCameraEvent::SampleType const> samplePtr)
{
    auto data = *samplePtr.Get();
    // put your logic
}
 
void RawData::SubscribeRField()
{
    if (m_found)
    {
        // regist receiver handler
        // if you want to enable it, please uncomment below code
        // 
        // RegistReceiverRField();
        
        // request subscribe
        auto subscribe = m_interface->RField.Subscribe(1);
        if (subscribe.HasValue())
        {
            m_logger.LogVerbose() << "RawData::SubscribeRField::Subscribed";
        }
        else
        {
            m_logger.LogError() << "RawData::SubscribeRField::" << subscribe.Error().Message();
        }
    }
}
 
void RawData::StopSubscribeRField()
{
    if (m_found)
    {
        // request stop subscribe
        m_interface->RField.Unsubscribe();
        m_logger.LogVerbose() << "RawData::StopSubscribeRField::Unsubscribed";
    }
}
 
void RawData::RegistReceiverRField()
{
    if (m_found)
    {
        // set callback
        auto receiver = [this]() -> void {
            return ReceiveFieldRFieldTriggered();
        };
        
        // regist callback
        auto callback = m_interface->RField.SetReceiveHandler(receiver);
        if (callback.HasValue())
        {
            m_logger.LogVerbose() << "RawData::RegistReceiverRField::SetReceiveHandler";
        }
        else
        {
            m_logger.LogError() << "RawData::RegistReceiverRField::SetReceiveHandler::" << callback.Error().Message();
        }
    }
}
 
void RawData::ReceiveFieldRFieldTriggered()
{
    if (m_found)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_interface->RField.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
        {
            auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->RField.GetNewSamples([&](auto samplePtr) {
                RawData::ReadValueRField(std::move(samplePtr));
            }));
            if (recv->HasValue())
            {
                m_logger.LogVerbose() << "RawData::ReceiveFieldRField::GetNewSamples::" << recv->Value();
            }
            else
            {
                m_logger.LogError() << "RawData::ReceiveFieldRField::GetNewSamples::" << recv->Error().Message();
            }
        }
    }
}
 
void RawData::ReceiveFieldRFieldCyclic()
{
    while (m_running)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        if (m_found)
        {
            if (m_interface->RField.GetSubscriptionState() == ara::com::SubscriptionState::kSubscribed)
            {
                auto recv = std::make_unique<ara::core::Result<size_t>>(m_interface->RField.GetNewSamples([&](auto samplePtr) {
                    RawData::ReadValueRField(std::move(samplePtr));
                }));
                if (recv->HasValue())
                {
                    m_logger.LogVerbose() << "RawData::ReceiveFieldRField::GetNewSamples::" << recv->Value();
                }
                else
                {
                    m_logger.LogError() << "RawData::ReceiveFieldRField::GetNewSamples::" << recv->Error().Message();
                }
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void RawData::ReadValueRField(ara::com::SamplePtr<deepracer::service::rawdata::proxy::fields::RField::FieldType const> samplePtr)
{
    auto value = *samplePtr.Get();
    // put your logic
}
 
void RawData::GetRField()
{
    if (m_found)
    {
        auto request = m_interface->RField.Get();
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RawData::GetRField::Responded";
            
            auto result = response.Value();
            // put your logic
        }
        else
        {
            m_logger.LogError() << "RawData::GetRField::" << response.Error().Message();
        }
    }
}
 
void RawData::SetRField(const deepracer::service::rawdata::proxy::fields::RField::FieldType& value)
{
    if (m_found)
    {
        auto request = m_interface->RField.Set(value);
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RawData::SetRField::Responded";
            
            auto result = response.Value();
            // put your logic
        }
        else
        {
            m_logger.LogError() << "RawData::GetRField::" << response.Error().Message();
        }
    }
}
 
void RawData::RequestRMethod(const double& a, const deepracer::type::Arithmetic& arithmetic, const double& b)
{
    if (m_found)
    {
        auto request = m_interface->RMethod(a, arithmetic, b);
        request.wait();
        auto response = request.GetResult();
        if (response.HasValue())
        {
            m_logger.LogVerbose() << "RawData::RequestRMethod::Responded";
            
            auto result = response.Value();
            // put your logic
        }
        else
        {
            m_logger.LogError() << "RawData::RequestRMethod::" << response.Error().Message();
        }
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace calc
 
/// EOF