///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : calc.h
/// SOFTWARE COMPONENT NAME           : Calc
/// GENERATED DATE                    : 2024-11-12 15:53:00
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_CALC_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_CALC_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "calc/aa/port/controldata.h"
#include "calc/aa/port/rawdata.h"
 
#include "para/swc/port_pool.h"
 
namespace calc
{
namespace aa
{
 
class Calc
{
public:
    /// @brief Constructor
    Calc();
    
    /// @brief Destructor
    ~Calc();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
 
private:
    /// @brief Run software component
    void Run();
 
private:
    void TaskReceiveREventCyclic();
    void OnReceiveREvent(const deepracer::service::rawdata::proxy::events::REvent::SampleType& sample);
    bool GetFrontLidarData(float start_degree, float end_degree, const deepracer::type::lidars before_lidar, deepracer::type::lidars* after_lidar);
    bool InterpolateLidarData(deepracer::type::lidars* lidar_datas);
    #if 0
    std::vector<float> Extract8PointsForAI(float start_degree, float end_degree, deepracer::type::lidars* lidar_datas);
    #else
    std::vector<float> Extract4PointsForAI(float start_degree, float end_degree, deepracer::type::lidars* lidar_datas);
    #endif
    void UpdateSteeringData(std::pair<float, float> steerDatas);
    std::pair <float, float> ConvertValueFromPredictToServo(std::pair<float, float> predictions);
    float GetMaxSpeed(float degree);
    void ThrowEventCyclic();
    /// @brief Pool of port
    
    bool m_running;
    bool m_event_flag;
    std::mutex m_mutex;
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Calc.ControlData}
    std::shared_ptr<calc::aa::port::ControlData> m_ControlData;
    
    /// @brief Instance of Port {Calc.RawData}
    std::shared_ptr<calc::aa::port::RawData> m_RawData;
};
 
} /// namespace aa
} /// namespace calc
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_CALC_AA_H